INSERT INTO USER (USER_ID,USER_NAME,PASSWORD,IS_ONLINE,PICTURE) VALUES (1,'member1','123456',0,'images/user/1.jpg');
INSERT INTO USER (USER_ID,USER_NAME,PASSWORD,IS_ONLINE,PICTURE) VALUES (2,'member2','123456',0,'images/user/2.jpg');
INSERT INTO USER (USER_ID,USER_NAME,PASSWORD,IS_ONLINE,PICTURE) VALUES (3,'member3','123456',0,'images/user/3.jpg');
INSERT INTO USER (USER_ID,USER_NAME,PASSWORD,IS_ONLINE,PICTURE) VALUES (4,'member4','123456',0,'images/user/4.jpg');
INSERT INTO USER (USER_ID,USER_NAME,PASSWORD,IS_ONLINE,PICTURE) VALUES (5,'member5','123456',0,'images/user/3.jpg');
INSERT INTO USER (USER_ID,USER_NAME,PASSWORD,IS_ONLINE,PICTURE) VALUES (5,'member6','123456',0,'images/user/3.jpg');

INSERT INTO FRIENDSHIP (FRIENDSHIP_ID,FRIEND_ID,USER_ID) VALUES (1,2,1);
INSERT INTO FRIENDSHIP (FRIENDSHIP_ID,FRIEND_ID,USER_ID) VALUES (2,3,1);
INSERT INTO FRIENDSHIP (FRIENDSHIP_ID,FRIEND_ID,USER_ID) VALUES (3,1,2);
INSERT INTO FRIENDSHIP (FRIENDSHIP_ID,FRIEND_ID,USER_ID) VALUES (4,3,2);
INSERT INTO FRIENDSHIP (FRIENDSHIP_ID,FRIEND_ID,USER_ID) VALUES (5,1,3);
INSERT INTO FRIENDSHIP (FRIENDSHIP_ID,FRIEND_ID,USER_ID) VALUES (6,2,3);
INSERT INTO FRIENDSHIP (FRIENDSHIP_ID,FRIEND_ID,USER_ID) VALUES (7,1,4);
INSERT INTO FRIENDSHIP (FRIENDSHIP_ID,FRIEND_ID,USER_ID) VALUES (8,2,4);
INSERT INTO FRIENDSHIP (FRIENDSHIP_ID,FRIEND_ID,USER_ID) VALUES (9,4,1);
INSERT INTO FRIENDSHIP (FRIENDSHIP_ID,FRIEND_ID,USER_ID) VALUES (10,4,2);

INSERT INTO GROUPS (GROUP_ID, GROUP_OWNER_ID, GROUP_NAME, GROUP_PIC) VALUES (1,1,'GROUP1','images/group/1.jpg');
INSERT INTO GROUPS (GROUP_ID, GROUP_OWNER_ID, GROUP_NAME, GROUP_PIC) VALUES (2,2,'GRoUP2','images/group/2.jpg');
INSERT INTO GROUPS (GROUP_ID, GROUP_OWNER_ID, GROUP_NAME, GROUP_PIC) VALUES (3,3,'Group3','images/group/3.jpg');
INSERT INTO GROUPS (GROUP_ID, GROUP_OWNER_ID, GROUP_NAME, GROUP_PIC) VALUES (3,3,'Group4','images/group/4.jpg');

INSERT INTO GROUP_REL (GROUP_REL_ID, GROUP_ID, GROUP_MEMBER_ID) VALUES (1,1,1);
INSERT INTO GROUP_REL (GROUP_REL_ID, GROUP_ID, GROUP_MEMBER_ID) VALUES (2,1,2);
INSERT INTO GROUP_REL (GROUP_REL_ID, GROUP_ID, GROUP_MEMBER_ID) VALUES (3,2,2);
INSERT INTO GROUP_REL (GROUP_REL_ID, GROUP_ID, GROUP_MEMBER_ID) VALUES (4,1,3);
INSERT INTO GROUP_REL (GROUP_REL_ID, GROUP_ID, GROUP_MEMBER_ID) VALUES (5,3,3);

INSERT INTO MESSAGE (MESSAGE_ID, SENDER_ID, SENDER_NAME, SENDER_PIC, RECEIVER_ID, SEND_TIME, MSG, TYPE) VALUES (1, 1, 'member1', 'images/user/1.jpg', 2, '2020-05-10 16:48:44.987515', 'hi,member2', 1);
INSERT INTO MESSAGE (MESSAGE_ID, SENDER_ID, SENDER_NAME, SENDER_PIC, RECEIVER_ID, SEND_TIME, MSG, TYPE) VALUES (2, 1, 'member1', 'images/user/1.jpg', 2, '2020-05-11 17:04:44.987515', '哈哈', 1);
INSERT INTO MESSAGE (MESSAGE_ID, SENDER_ID, SENDER_NAME, SENDER_PIC, RECEIVER_ID, SEND_TIME, MSG, TYPE) VALUES (3, 1, 'member1', 'images/user/1.jpg', 3, '2020-05-12 22:43:44.987515', 'hello', 1);
INSERT INTO MESSAGE (MESSAGE_ID, SENDER_ID, SENDER_NAME, SENDER_PIC, RECEIVER_ID, SEND_TIME, MSG, TYPE) VALUES (4, 2, 'member2', 'images/user/2.jpg', 1, '2020-05-13 12:21:44.987515', '？?，,。.', 1);
INSERT INTO MESSAGE (MESSAGE_ID, SENDER_ID, SENDER_NAME, SENDER_PIC, RECEIVER_ID, SEND_TIME, MSG, TYPE) VALUES (5, 2, 'member2', 'images/user/2.jpg', 1, '2020-05-14 15:34:44.987515', '今晚出去吃饭吗？', 1);
INSERT INTO MESSAGE (MESSAGE_ID, SENDER_ID, SENDER_NAME, SENDER_PIC, RECEIVER_ID, SEND_TIME, MSG, TYPE) VALUES (6, 2, 'member2', 'images/user/2.jpg', 3, '2020-05-15 13:46:41.987515', 'hi,member', 1);
INSERT INTO MESSAGE (MESSAGE_ID, SENDER_ID, SENDER_NAME, SENDER_PIC, RECEIVER_ID, SEND_TIME, MSG, TYPE) VALUES (7, 3, 'member3', 'images/user/3.jpg', 1, '2020-05-16 18:08:44.987515', 'hi,member', 1);
INSERT INTO MESSAGE (MESSAGE_ID, SENDER_ID, SENDER_NAME, SENDER_PIC, RECEIVER_ID, SEND_TIME, MSG, TYPE) VALUES (8, 3, 'member3', 'images/user/3.jpg', 2, '2020-05-17 20:18:41.987515', 'hi,member', 1);
INSERT INTO MESSAGE (MESSAGE_ID, SENDER_ID, SENDER_NAME, SENDER_PIC, RECEIVER_ID, SEND_TIME, MSG, TYPE) VALUES (9, 3, 'member3', 'images/user/3.jpg', 1, '2020-05-18 09:46:41.987515', 'hi,group1', 2);
INSERT INTO MESSAGE (MESSAGE_ID, SENDER_ID, SENDER_NAME, SENDER_PIC, RECEIVER_ID, SEND_TIME, MSG, TYPE) VALUES (10, 1, 'member1', 'images/user/1.jpg', 1, '2020-05-19 02:58:14.987515', 'GGG', 2);
INSERT INTO MESSAGE (MESSAGE_ID, SENDER_ID, SENDER_NAME, SENDER_PIC, RECEIVER_ID, SEND_TIME, MSG, TYPE) VALUES (11, 2, 'member2', 'images/user/2.jpg', 1, '2020-05-20 10:00:54.987515', '哦', 2);
INSERT INTO MESSAGE (MESSAGE_ID, SENDER_ID, SENDER_NAME, SENDER_PIC, RECEIVER_ID, SEND_TIME, MSG, TYPE) VALUES (12, 3, 'member3', 'images/user/3.jpg', 1, '2020-05-21 10:11:24.987515', 'hi', 2);